#ble_proxy 蓝牙代理
#ble_monitor 蓝牙网关
#Coordinator zigbee协调器
#Router zigbee路由器
#factory 拆机串口刷机固件

[$]esphome_tube_zb_gw_efr32_factory.bin  [$]编程器固件,串口刷机固件

[$]esphome_tube_zb_gw_efr32.bin  [$]zigbee协调器+蓝牙代理+蓝牙网关(常闭),OTA固件

[$]esphome_tube_zb_gw_efr32_zigbee.bin  [$]只有zigbee协调器,OTA固件

[$]esphome_tube_zb_gw_efr32_ble_monitor.bin  [$]zigbee协调器+蓝牙网关,OTA固件

[$]esphome_tube_zb_gw_efr32_ble_proxy.bin  [$]zigbee协调器+蓝牙代理,OTA固件
